'use strict';

const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('ksfAssistant', Object.freeze({
  dashboard: () => ipcRenderer.invoke('dashboard:read'),
  tokenHistory: (options = { dayCount: 30 }) => ipcRenderer.invoke('token-history:read', options),
  pricingCatalog: () => ipcRenderer.invoke('pricing-catalog:read'),
  settings: () => ipcRenderer.invoke('settings:read'),
  updateSettings: (patch) => ipcRenderer.invoke('settings:update', patch),
  openExternal: (url) => ipcRenderer.invoke('external:open', url),
  chooseDirectory: (kind) => ipcRenderer.invoke('directory:choose', kind),
  setPinned: (projectId, pinned) => ipcRenderer.invoke('project:set-pinned', { projectId, pinned }),
  openPath: (targetPath) => ipcRenderer.invoke('path:open', targetPath),
  openTask: (threadId) => ipcRenderer.invoke('task:open', threadId),
  createTask: (projectId, purpose) => ipcRenderer.invoke('task:create', { projectId, purpose }),
  launchProject: (projectId) => ipcRenderer.invoke('project:launch', projectId),
  createTaskLink: (payload) => ipcRenderer.invoke('feishu:task-link-create', payload),
  releaseTaskLink: (payload) => ipcRenderer.invoke('feishu:task-link-release', payload),
  interruptTaskLink: (payload) => ipcRenderer.invoke('feishu:task-link-interrupt', payload),
  sendFeishuTest: (targetAlias) => ipcRenderer.invoke('feishu:test', targetAlias),
  setFeishuProfile: (profile) => ipcRenderer.invoke('feishu:profile-set', profile),
  readFeishuSetup: () => ipcRenderer.invoke('feishu:setup-read'),
  beginFeishuSetup: (payload) => ipcRenderer.invoke('feishu:setup-begin', payload),
  continueFeishuSetup: () => ipcRenderer.invoke('feishu:setup-continue'),
  verifyFeishuSetup: () => ipcRenderer.invoke('feishu:setup-verify'),
  activateFeishuSetup: (targetAlias) => ipcRenderer.invoke('feishu:setup-activate', targetAlias),
  cancelFeishuSetup: () => ipcRenderer.invoke('feishu:setup-cancel'),
  feishuOverview: () => ipcRenderer.invoke('feishu:overview-read'),
  feishuAuthStatus: () => ipcRenderer.invoke('feishu:auth-status'),
  startFeishuAuth: () => ipcRenderer.invoke('feishu:auth-start'),
  finishFeishuAuth: () => ipcRenderer.invoke('feishu:auth-finish'),
  logoutFeishuAuth: (confirm) => ipcRenderer.invoke('feishu:auth-logout', confirm),
  toolchainStatus: () => ipcRenderer.invoke('toolchain:status'),
  installToolchain: (confirm) => ipcRenderer.invoke('toolchain:install', confirm),
  updateFeishuFeature: (payload) => ipcRenderer.invoke('feishu:feature-update', payload),
  restartFeishu: () => ipcRenderer.invoke('feishu:supervisor-restart'),
  openFeishuURL: (url) => ipcRenderer.invoke('feishu:open-external', url),
  resize: (height) => ipcRenderer.send('window:resize', height),
  hide: () => ipcRenderer.send('window:hide'),
  quit: () => ipcRenderer.send('app:quit'),
}));
